apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
  name: sklearn-iris
spec:
  predictor:
    sklearn:
      storageUri: s3://aws-dvc-2025/models/iris/7fd3005e4a29445c8c16247a38ed70fa
